sudo: required
dist: trusty
language: cpp

compiler:
    - g++

before_install:
    - sudo apt-get install -y software-properties-common
    - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -y update

install:
    - sudo pip install -y cpp-coveralls
    - sudo apt-get install -y cppcheck
    - sudo apt-get install -y libgtest-dev
    - sudo apt-get install -y g++-5
    - sudo apt-get install -y flex bison
    - sudo apt-get install -y cmake
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50
    - sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 50
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make
    - "cd ./test ; ctest ; cd -"
    - ./../analyze_static.sh

after_success:
    - coveralls --root .. -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"
