language: cpp

compiler:
    - g++

before_install:
    - sudo apt-get install -y software-properties-common
    - sudo add-apt-repository -y ppa:george-edison55/precise-backports
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -y update


install:
    - sudo apt-get install -y cppcheck
    - sudo apt-get install -y libgtest-dev
    - sudo apt-get install -y g++-5
    - sudo apt-get install -y flex bison
    - sudo apt-get install -y cmake
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50
    - sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 50

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make
    - ctest
    - ./analize_static.sh
